<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<!-- Mirrored from openhome.cc/Gossip/JUnit/TestCase.html by HTTrack Website Copier/3.x [XR&CO'2008], Sun, 28 Jul 2013 09:19:22 GMT -->
<head>
  
  <link rel="stylesheet" href="css/stdlayout.css" type="text/css">

  
  <link rel="stylesheet" href="css/print.css" type="text/css">

  
  <meta content="text/html; charset=Big5" http-equiv="content-type">
  <title>關於 TestCase</title>

  
</head><body>
<h3><a href="../index.html">From
Gossip@Openhome</a></h3>

<h1><a href="index-2.html">JUnit Gossip: 關於 TestCase<br>
</a></h1>

<table style="text-align: left; width: 946px; height: 32px;" border="0" cellpadding="0" cellspacing="0">

  <tbody>
    <tr>
      <td style="vertical-align: top; width: 250px; text-align: center;">
      <script type="text/javascript"><!--
google_ad_client = "pub-9750319131714390";
google_ad_width = 160;
google_ad_height = 600;
google_ad_format = "160x600_as";
google_ad_type = "text_image";
google_ad_channel = "";
//-->
      </script>
      <script type="text/javascript" src="../../../pagead2.googlesyndication.com/pagead/show_ads.js">
      </script><br>
      <br>
<script type="text/javascript"><!--
google_ad_client = "pub-9750319131714390";
google_ad_width = 160;
google_ad_height = 600;
google_ad_format = "160x600_as";
google_ad_type = "text_image";
google_ad_channel = "";
//-->
</script>
<script type="text/javascript" src="../../../pagead2.googlesyndication.com/pagead/show_ads.js">
</script><br>
<br>
      <script type="text/javascript"><!--
google_ad_client = "pub-9750319131714390";
google_ad_width = 160;
google_ad_height = 600;
google_ad_format = "160x600_as";
google_ad_type = "text_image";
google_ad_channel = "";
//-->
      </script>
      <script type="text/javascript" src="../../../pagead2.googlesyndication.com/pagead/show_ads.js">
      </script><br>
      <br>
      <center>
       </center>
      </td>
      <td style="vertical-align: top; width: 690px; text-align: left;"><small>在
      </small><small><a href="JUnit3.html">使用 JUnit 3.x</a> 中介紹的，幾乎就是使用<span style="font-family: Courier New,Courier,monospace;">TestCase最常見的方式了，這邊要
來深入討論一下TestCase</span>。</small><br>
      <small><br>
在JUnit 3.x中撰寫測試案例，必須繼承<span style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">TestCase</span>類別，TestCase類別繼承自<span style="font-weight: bold;">Assert</span>類別，最主要的目的，是方便使用Assert類別中定義的諸多靜態
方法，諸如assertXXX()、fail()等斷言方法。<br>
      <br>
assertXXX()方法無需太多解釋，XXX名稱各指出斷言某個情況。fail()方法值得略為一題，呼叫了fail()方法必然丟出錯誤
（Error），因為其於Assert中的定義為：<br>
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; static public
void fail(String message) {</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; throw new AssertionFailedError(message);</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; }</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; static public
void fail() {</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; fail(null);</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; }</span><br>
      <br>
fail()使用的時機之一，就是在撰寫測試案例時，於每個testXXX()中先失敗作為開始。例如：<br>
      </span></small>
      <div style="margin-left: 40px;"><small><span style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">public void testABC() {</span></span></small><br style="font-weight: bold;">
      <small><span style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; fail("單元測試尚未撰寫");</span></span></small><br style="font-weight: bold;">
      <small><span style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">}</span></span></small><br>
      <small><span style="font-family: Courier New,Courier,monospace;"></span></small></div>
      <small><span style="font-family: Courier New,Courier,monospace;"><br>
在</span>IDE<span style="font-family: Courier New,Courier,monospace;">自動程
式碼產生測試案例時，通常都會自動填上fail()，以提醒開發人員尚有單元測試未撰寫。fail()使用的另一個例子，就是測試例外是否發生。例如：<br>
      </span></small>
      <div style="margin-left: 40px;"><small style="font-weight: bold;"><span style="font-family: Courier New,Courier,monospace;">public void
testSomeException() {</span></small><br style="font-weight: bold;">
      <small style="font-weight: bold;"><span style="font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;
try {</span></small><br style="font-weight: bold;">
      <small style="font-weight: bold;"><span style="font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
some.doSome("somValue");&nbsp; // 應該丟出例外</span></small><br style="font-weight: bold;">
      <small style="font-weight: bold;"><span style="font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
fail("沒有如預期丟出例外");</span></small><br style="font-weight: bold;">
      <small style="font-weight: bold;"><span style="font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;
}</span></small><br style="font-weight: bold;">
      <small style="font-weight: bold;"><span style="font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;
catch(SomeException ex) {</span></small><br style="font-weight: bold;">
      <small style="font-weight: bold;"><span style="font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
// 什麼都不作</span></small><br style="font-weight: bold;">
      <small style="font-weight: bold;"><span style="font-family: Courier New,Courier,monospace;">&nbsp;&nbsp;&nbsp;
}</span></small><br style="font-weight: bold;">
      <small style="font-weight: bold;"><span style="font-family: Courier New,Courier,monospace;">}</span></small><br>
      <small><span style="font-family: Courier New,Courier,monospace;"></span></small></div>
      <small><span style="font-family: Courier New,Courier,monospace;"><br>
上例中，預期doSome()方法會丟出例外，如果實際上測試沒有丟出例外，那麼就會執行到fail()方法，表示測試失敗，如果如預期丟出例外，則會被
捕捉（catch），此時什麼都不作，表示測試成功。。<br>
      <br>
TestCase除了繼承Assert類別外，還實作了Test介面：<br>
      </span></small>
      <div style="margin-left: 40px;"><small><span style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">public abstract class TestCase extends
Assert implements Test {</span></span></small><br>
      <small><span style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; ...</span></span></small><br>
      <small><span style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">}</span></span></small><br>
      <small><span style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;"></span></span></small></div>
      <small><span style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;"><br>
      </span>正如之前的範例探討，TestCase實作Test介面，是為了以 </span><span class="Apple-style-span" style="border-collapse: separate; color: rgb(0, 0, 0); font-family: Arial; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; font-size: medium;"><span class="Apple-style-span" style="font-family: serif; font-size: 14px; text-align: left;"><a href="../DesignPattern/CommandPattern.htm" style="color: rgb(68, 68, 68); font-weight: bold; text-decoration: none;">Command
模式</a></span></span></small><small><span style="font-family: Courier New,Courier,monospace;"> 實現測試之執行，在</span>JUnit
3.x<span style="font-family: Courier New,Courier,monospace;">的設計中，最後會以反射
方式執行測試方法（無論是預設的testXXX()或是自行指定的測試方法），而在執行測試方法前，會運行setUp()與tearDown()：<br>
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; protected
void setUp() throws Exception {</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; }</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; protected
void tearDown() throws Exception {</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; }</span><br>
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; public void
runBare() throws Throwable {</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; setUp();</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; try {</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; runTest();</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; }</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; finally {</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; tearDown();</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; }</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; }<br>
&nbsp;&nbsp;&nbsp; protected void runTest() throws Throwable {<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ...以反射運行測試方法<br>
&nbsp;&nbsp;&nbsp; }<br>
      </span><span style="font-weight: bold;"></span><br>
這也就是為何可以定義<span style="font-weight: bold;">setUp()</span>與<span style="font-weight: bold;">tearDown()</span>，於每次testXXX()（或指定的測試方法）前後執行
之。<br>
      <br>
在執行測試時，你會發現到有</span><span style="font-weight: bold;">Failure</span>與<span style="font-weight: bold;">Error</span><span style="font-family: Courier New,Courier,monospace;">兩種測試尚未通過的訊息。<br>
      <br>
      </span>Failure<span style="font-family: Courier New,Courier,monospace;">指的是預期結果與實際運行結果不同，例如
當你使用assertEquals()或其它assertXXX()方法斷言失敗時，就會回報</span>Failure<span style="font-family: Courier New,Courier,monospace;">，這時候你要檢查你的單元方法中的邏輯設
計是否有誤。<br>
      <br>
      </span>Error<span style="font-family: Courier New,Courier,monospace;">指的是程式在斷言方法執行之前，程式就因
為某種錯誤引發例外而終止，例如在測試方法中因丟出某個例外，使得測試方法無法正確執行至斷言就提前結束，這時你要檢查測試方法中是否有未考慮到的情況而
引發流程突然中斷。<br>
      <br>
如果你檢視Test介面的定義，會發現它定義的run()方法有傳入<span style="font-weight: bold;">TestResult</span>：<br>
      </span></small>
      <div style="margin-left: 40px;"><small><span style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">public abstract void run(TestResult result);</span></span></small><br>
      <small><span style="font-family: Courier New,Courier,monospace;"></span></small></div>
      <small><span style="font-family: Courier New,Courier,monospace;"><br>
TestResult會收集測試過程中所有單元測試的結果，</span>Failure與Error<span style="font-family: Courier New,Courier,monospace;">各收集在一個Vector中：<br>
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; public
synchronized void addError(Test test, Throwable t) {</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; fErrors.addElement(new TestFailure(test, t));</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; for (Enumeration e= cloneListeners().elements();
e.hasMoreElements(); ) {</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;
((TestListener)e.nextElement()).addError(test, t);</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; }</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; }</span><br style="font-weight: bold;">
      <br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; public
synchronized void addFailure(Test test, AssertionFailedError t) {</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; fFailures.addElement(new TestFailure(test, t));</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; for (Enumeration e= cloneListeners().elements();
e.hasMoreElements(); ) {</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;
((TestListener)e.nextElement()).addFailure(test, t);</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; }</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; }</span><br>
      <br>
如果你使用</span>JUnit<span style="font-family: Courier New,Courier,monospace;">的TestRunner，則
TestRunner會為你建立TestResult。TestCase提供了一個公開的run()方法，會建立預設的TestResult來運行測試：<br>
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; protected
TestResult createResult() {</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; return new TestResult();</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; }</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; public
TestResult run() {</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; TestResult result= createResult();</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; run(result);</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; return result;</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; }</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; public void
run(TestResult result) {</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; result.run(this);</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; }</span><br>
      <br>
簡單地說，如果你不想透過TestRunner，則可以簡單的呼叫run()方法，而後取得TestResult來查看測試結果。例如：<br>
      </span></small>
      <ul>
        <li><small>CalculatorTest.java</small></li>
      </ul>
      <pre>package cc.openhome;<br><br>import junit.framework.TestCase;<br>import junit.framework.TestResult;<br><br>public class CalculatorTest extends TestCase {<br>    private Calculator calculator;<br>    <br>    public CalculatorTest() {}<br>    <br>    public CalculatorTest(String name) {<br>        super(name);<br>    }<br>    <br>    @Override<br>    protected void setUp() {<br>        calculator = new Calculator();<br>    }<br><br>    @Override<br>    protected void tearDown() {<br>        calculator = null;<br>    }<br><br>    public void testPlus() {<br>        int expected = 5;<br>        int result = calculator.plus(3, 2);<br>        assertEquals(expected, result);<br>    }<br>    <br>    public void testMinus() {<br>        int expected = 1;<br>        int result = calculator.minus(3, 2);<br>        assertEquals(expected, result);<br>    }<br><br>    public static void main(String[] args) {<br style="font-weight: bold;"><span style="font-weight: bold;">        CalculatorTest[] calculatorTests = {</span><br style="font-weight: bold;"><span style="font-weight: bold;">                new CalculatorTest("testPlus"), </span><br style="font-weight: bold;"><span style="font-weight: bold;">                new CalculatorTest("testMinus")};<br><br style="font-weight: bold;"></span><span style="font-weight: bold;">        for(CalculatorTest test: calculatorTests) {</span><br style="font-weight: bold;"><span style="font-weight: bold;">            TestResult result = test.run();</span><br style="font-weight: bold;"><span style="font-weight: bold;">            System.out.println(test.getName());</span><br style="font-weight: bold;"><span style="font-weight: bold;">            System.out.println("\tError: " + result.errorCount());</span><br style="font-weight: bold;"><span style="font-weight: bold;">            System.out.println("\tFailure: " + result.failureCount());</span><br style="font-weight: bold;"><span style="font-weight: bold;">        }       </span><br>    }<br>}<br></pre>
      <small><span style="font-family: Courier New,Courier,monospace;"><br>
如果你對於</span>Failure與Error<span style="font-family: Courier New,Courier,monospace;">、測試開始與結束有興趣，並想作一些處
理，則可以實作<span style="font-weight: bold;">TestListener</span>：<br>
      </span></small>
      <div style="margin-left: 40px;"><small><span style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">public interface TestListener {</span></span></small><br style="font-weight: bold;">
      <small><span style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; public void
addError(Test test, Throwable t);</span></span></small><br style="font-weight: bold;">
      <small><span style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; public void
addFailure(Test test, AssertionFailedError t);&nbsp; </span></span></small><br style="font-weight: bold;">
      <small><span style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; public void endTest(Test
test); </span></span></small><br style="font-weight: bold;">
      <small><span style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp; public void
startTest(Test test);</span></span></small><br style="font-weight: bold;">
      <small><span style="font-family: Courier New,Courier,monospace;"><span style="font-weight: bold;">}</span></span></small><br>
      <small><span style="font-family: Courier New,Courier,monospace;"></span></small></div>
      <small><span style="font-family: Courier New,Courier,monospace;"><br>
之後透過TestResult的<span style="font-weight: bold;">addListener()</span>加入實作
的傾聽器，則在</span></small><small><span style="font-family: Courier New,Courier,monospace;"></span>Failure與
Error<span style="font-family: Courier New,Courier,monospace;">、測試開始與結束，
TestResult都會通知你的傾聽器，讓你作適當的處理。例如：<br>
&nbsp;<span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
...</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
CalculatorTest[] calculatorTests = {</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
new CalculatorTest("testPlus"), </span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
new CalculatorTest("testMinus")};<br>
      <br style="font-weight: bold;">
      </span><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
TestResult result = new TestResult();<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; result.addListener(new
TestListener() {<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; //
方法的實作<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; });<br style="font-weight: bold;">
      </span><span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
for(CalculatorTest test: calculatorTests) {</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
test.run(result);</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
}</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      </span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
for(Enumeration e = result.failures(); e.hasMoreElements();) {</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; TestFailure failure = (TestFailure) e.nextElement();</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; System.out.print(failure.isFailure() ? "Failure: " :
"Error: ");</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; System.out.println(failure.exceptionMessage());</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp; System.out.println(failure.trace());</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
}</span><br style="font-weight: bold;">
      <span style="font-weight: bold;">&nbsp; &nbsp; &nbsp; &nbsp; ...
&nbsp;&nbsp;&nbsp; </span><br>
      <br>
無論是</span>Failure或Error<span style="font-family: Courier New,Courier,monospace;">，都使用TestFailure封裝，可
使用isFailure()來判斷是否為</span>Failure<span style="font-family: Courier New,Courier,monospace;">。<br>
      <br>
      </span></small><small><span style="font-family: Courier New,Courier,monospace;"><br>
      </span></small></td>
    </tr>
  </tbody>
</table>

<br>

<br>

<br>

<br>

<script src="../../../www.google-analytics.com/urchin.js" type="text/javascript">
</script>
<script type="text/javascript">
_uacct = "UA-143766-1";
urchinTracker();
</script>
</body>
<!-- Mirrored from openhome.cc/Gossip/JUnit/TestCase.html by HTTrack Website Copier/3.x [XR&CO'2008], Sun, 28 Jul 2013 09:19:22 GMT -->
</html>